dist: trusty
sudo: false
language: node_js

before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm i -g greenkeeper-lockfile@2

install:
  - pnpm recursive install

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - ./build_and_test.sh
