dist: trusty
sudo: false
language: node_js

before_install: yarn global add greenkeeper-lockfile@2
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - ./build_and_test.sh
